name: "Server Deployment"
on:
  push:
      branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
          switches: -avzr --delete
          path: /Users/hillary.sandersopendoor.com/noisedive-flask
          remote_path: /home/noisedive-flask
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: 8000
    run:
      mkdir -p noisedive-flask  # make server folder if it does not already exist
      echo "Hello there!"
      echo `whoami`
      echo $GITHUB_WORKSPACE
      echo `pwd`
      echo `ls`


    # env:
    #   GITHUB_WORKSPACE: ${{ github.workspace }}  # Set the environment variable for github.workspace
    #   SSH_HOST: ${{ secrets.SSH_HOST }}
    #   SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
    #   SSH_KEY: ${{ secrets.SSH_KEY }}
    #   SSH_PORT: 8000

    # run:
    #   mkdir -p noisedive-flask  # make server folder if it does not already exist
    #   rsync -avzhr /Users/hillary.sandersopendoor.com/noisedive-flask ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/noisedive-flask/