name: scp files to server
on: 
  push:
    branches: [main]
jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
    - name: Delete files in ssh server
      uses: appleboy/ssh-action@master
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}  # Set the environment variable for github.workspace
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        # Recursively delete:
        script: rm -rfd /home/public/ && mkdir /home/public/

  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    # # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     echo -e " ${{ secrets.SSH_KEY }} " >__TEMP
    #     scp -v -i __TEMP index.html ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/public/noisedive/index.html
    #     rm __TEMP

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ./
        target: /home/public/


# TODO: I think the git repo needs to be named noisedive_flask instead of noisedive-flask... Did that. Redo all?
# And eventually I think all you do is:
# ### ON REMOTE MACHINE:
# python3.10 -m venv venv
# source venv/bin/activate
# pip install -r requirements.txt

# pip install wheel
# python setup.py bdist_wheel

# ### potentially on new machine or different directory, using the version (here 1.1 listed in setup.py)
# python3.10 -m venv wheel_venv
# source wheel_venv/bin/activate
# pip install dist/noisedive_flask-1.1-py3-none-any.whl --force-reinstall

# ## WSGI server:
# pip install waitress
# venv/bin/waitress-serve --call 'noisedive_flask:create_app'

