name: "Server Deployment"
on:
  push:
      branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Make folder
      run: |
        mkdir -p noisedive-flask  # make server folder if it does not already exist
        echo "Hello there!"
        echo `whoami`
        echo $GITHUB_WORKSPACE
        echo `pwd`
        echo `ls`
        echo `ls noisedive-flask`

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload to SSH Server
      uses: appleboy/ssh-action@master
      # uses: burnett01/rsync-deployments@5.2.1
      env:
          # switches: -avzr --delete
          path: src/index.html
          remote_path: /home/public
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 8000
      run: |
        echo -e "${{ secrets.SSH_KEY }}" >__TEMP_INPUT_KEY_FILE
        chmod 600 __TEMP_INPUT_KEY_FILE
        echo "Hello there!"
        echo `whoami`
        echo $GITHUB_WORKSPACE
        echo `pwd`
        echo `ls`
        echo hi && scp -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE $GITHUB_WORKSPACE/index.html ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/public/
