name: scp files to server
on: 
  push:
    branches: [main]
jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
    - name: Delete files in ssh server
      uses: appleboy/ssh-action@master
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}  # Set the environment variable for github.workspace
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        # Recursively delete everything except venv and folder itself, for now (rsync better probs, but meh).
        # TODO: this deletes the DBs each time, remove them from git, probably, and add init steps to setup steps.
        script: find /home/protected/noisedive -maxdepth 1 -mindepth 1 -not -name /home/protected/noisedivevenv -not -name /home/protected/noisedive/wheel_venv -delete
  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    # # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     echo -e " ${{ secrets.SSH_KEY }} " >__TEMP
    #     scp -v -i __TEMP index.html ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/public/noisedive/index.html
    #     rm __TEMP

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ./
        target: /home/protected/noisedive


# TODO: I think the git repo needs to be named noisedive_flask instead of noisedive-flask... Did that. Redo all?
# And eventually I think all you do is:
# ### ON REMOTE MACHINE:
# python3.10 -m venv venv
# source venv/bin/activate
# pip install --upgrade pip
# pip install -r requirements.txt

# pip install wheel
# python setup.py bdist_wheel

# ### NOTE: updates seem to not go through unless version is increased??
# ### potentially on new machine or different directory, using the version (here 1.1 listed in setup.py)
# ### (not needed I think) python3.10 -m venv wheel_venv
# ### (not needed I think) source wheel_venv/bin/activate
# pip install dist/noisedive_flask-1.1-py3-none-any.whl --force-reinstall

# ## WSGI server:
# pip install waitress
# venv/bin/waitress-serve --call 'noisedive_flask:create_app'



# ### EACH TIME:
# source venv/bin/activate
# python setup.py bdist_wheel
# ### (not needed I think) source wheel_venv/bin/activate
# pip install dist/noisedive_flask-1.1.3-py3-none-any.whl
# venv/bin/waitress-serve --call 'noisedive_flask:create_app'

#### NOTES: works great locally. Seems to run remotely, but I can't find it online. Might need to use nginx or something, or it's something else.



######
# added sh file:
# # touch /home/protected/run-noisedive.sh
# #!/bin/sh
# # then:
# chmod a+x run-noisedive.sh
# # you can test with:
# cd noisedive
# ../run-noisedive.sh


# exec venv/bin/waitress-serve --call 'noisedive_flask:create_app'