name: "Server Deployment"
on:
  push:
      branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Make folder
      run: |
        mkdir -p noisedive-flask  # make server folder if it does not already exist
        echo "Hello there!"
        echo `whoami`
        echo $GITHUB_WORKSPACE
        echo `pwd`
        echo `ls`

    - uses: actions/checkout@v2
    - name: rsync deployments
      # uses: burnett01/rsync-deployments@5.2.1
      env:
          # switches: -avzr --delete
          path: src/index.html
          remote_path: /home/public
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: 8000
      run: |
        echo -e "${{ secrets.SSH_KEY }}" >__TEMP_INPUT_KEY_FILE
        chmod 600 __TEMP_INPUT_KEY_FILE
        scp -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE -P "8000" -r index.html ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/public/

        # scp -o StrictHostKeyChecking=no index.html ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/public/


    # env:
    #   GITHUB_WORKSPACE: ${{ github.workspace }}  # Set the environment variable for github.workspace
    #   SSH_HOST: ${{ secrets.SSH_HOST }}
    #   SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
    #   SSH_KEY: ${{ secrets.SSH_KEY }}
    #   SSH_PORT: 8000

    # run:
    #   mkdir -p noisedive-flask  # make server folder if it does not already exist
    #   rsync -avzhr /Users/hillary.sandersopendoor.com/noisedive-flask ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/noisedive-flask/