name: "Server Deployment"

on:

  push:

      branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

    - name: Say Hello!
    uses: actions/checkout@v2
    run:
      echo "Hello there!"
      echo `whoami`
      echo $GITHUB_WORKSPACE
      echo `pwd`
      echo `ls`

    - name: Deploy code to server with rsync
    env:
      GITHUB_WORKSPACE: ${{ github.workspace }}  # Set the environment variable for github.workspace
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

    run:
      mkdir -p noisedive-flask  # make server folder if it does not already exist
      rsync -avzhr /Users/hillary.sandersopendoor.com/noisedive-flask ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/noisedive-flask/