name: scp files to server
on: 
  push:
    branches: [main]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    # # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     echo -e " ${{ secrets.SSH_KEY }} " >__TEMP
    #     scp -v -i __TEMP index.html ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/public/noisedive/index.html
    #     rm __TEMP

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ./
        target: /home/public/



# TODO: LOL, okay the flask code is all python 3.10, and nearlyfreespeech server is python 3.9. Not sure how to change.
# So maybe just create your own flask app, or port back. But the scp upload is working!!!
# And eventually I think all you do is:
# ### ON REMOTE MACHINE:
# python3.10 -m venv venv
# source venv/bin/activate
# pip install -r requirements.txt

# pip install wheel
# python setup.py bdist_wheel
# ### potentially on new machine or different directory:
# pip install dist/noisedive_flask-1.0-py3-none-any.whl

# ## WSGI server:
# pip install waitress
# venv/bin/waitress-serve --call 'noisedive_flask:create_app'

