name: scp files to server
on: 
  push:
    branches: [main]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    # # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     mkdir ../build
    #     cp -TR . ../build
    #     tar -cvf deploy.tar ../build/

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        source: index.html
        target: /home/public/index.html


