name: ssh commands on server

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to SSH Server
      uses: appleboy/ssh-action@master
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}  # Set the environment variable for github.workspace
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        # run some set of commands on the server:
        script: echo -e "HELLO THERE!" >__TEMP_INPUT_KEY_FILE

    - name: Notify Deployment Success
      run: echo "Deployment to remote server completed successfully!"