name: scp files
on: 
  push:
    branches: [main]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "index.html"
        target: /home/public


# name: "Server Deployment"
# on:
#   push:
#       branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Make folder
#         run: |
#           mkdir -p noisedive-flask  # make server folder if it does not already exist
#           echo "Hello there!"
#           echo `whoami`
#           echo $GITHUB_WORKSPACE
#           echo `pwd`
#           echo `ls`
#           echo `ls noisedive-flask`

#       - uses: actions/checkout@v2
#       - name: rsync deployments
#       # - name: Upload to SSH Server
#       #   uses: appleboy/ssh-action@master
#         # uses: burnett01/rsync-deployments@5.2.1
#         env:
#             # switches: -avzr --delete
#             path: src/index.html
#             remote_path: /home/public
#             host: ${{ secrets.SSH_HOST }}
#             username: ${{ secrets.SSH_USERNAME }}
#             key: ${{ secrets.SSH_KEY }}
#             port: 8000
#         run: |
#           echo -e "${{ secrets.SSH_KEY }}" >__TEMP
#           chmod 600 __TEMP
#           echo "Hello there!"
#           echo `whoami`
#           echo $GITHUB_WORKSPACE
#           echo `pwd`
#           echo `ls`
#           scp -o StrictHostKeyChecking=no -v -i __TEMP $GITHUB_WORKSPACE/index.html ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/public/
#           echo Done
